### ISSUE TITLE
What type of mobs can be turned into familiars? just asking.

### ISSUE THREAD

**Issue by UwUsheep** [SoSly/ArcaneAdditions#111]
So.. What type of mobs can be bounded?

**Comment by celestmia** [comment]
I was looking for the answer to this as well! By default: Bat, Cat, Parrot, Fox, Rabbit, Chicken and Allay.

It's defined in the server config `arcaneadditions-server.toml`:

```toml
#Familiar settings
[familiars]
	#A list of entity types that can be bound as familiars.
	familiars = ["minecraft:bat", "minecraft:cat", "minecraft:parrot", "minecraft:fox", "minecraft:rabbit", "minecraft:chicken", "minecraft:allay"]
```
