### ISSUE TITLE
Make plow not hardcoded to what blocks it can plow

### ISSUE THREAD

**Issue by Slickson77** [SoSly/ArcaneAdditions#112]
say no to hardcoded blocks.  Plow doesn't work on Farmers Delight Rich Soil :(

Oof. So it's an immutable map right now.  Grass Block, Dirt Path, Dirt, Coarse Dirt, and Rooted Dirt.

I did a small amount of digging into tags and I don't see a commonality, I have 0 clue how Minecraft handles this.

**Comment by nivthefox** [comment]
Yeah, that's why it's hardcoded.  What I wish I could do is add a configuration for it, but then I'd need to configure both input and output I think?  Alternatively I can write a compat.

I'll think on this some.

**Comment by nivthefox** [comment]
What I'm going to do is add a new section to the configuration that looks like this:

```toml
# Plow settings
[plow]
    [[plow.blocks]]
    from = "minecraft:grass_block"
    to = "minecraft:farmland"

    [[plow.blocks]]
    from = "minecraft:rooted_dirt"
    to = "minecraft:dirt"
    drops = ["minecraft:hanging_roots"]
    needs_air = false

    [[plow.blocks]]
    from = "farmersdelight:rich_soil"
    to = "minecraft:farmland"
```

At least this will let you add compatibility with whatever mods you want.
